### PR TITLE
Relative output path support, among other little things

### PR DESCRIPTION
**Pull request by felipejoribeiro**
- Relative path support was added;
- Some structural changes were made to `utils.lua`;
- File name formatting was changed to include additional information;

Pending changes for better integration with base package:
- Make name formatting optional with a new option in the configs;
- Add `Adobe Illustrator` support again, using the new `utils.lua` functions;
- Row back the breaking changes made to the configs;

ps: Sorry for not creating a new branch and not being more careful with breaking changes. I will implement these corrections myself.

### CODE REVIEW

**Comment by rpapallas** [comment]
Hi Felipe,

Thank you for the PR and the improvements. Regarding the inkscape issue and the use of `sudo` in your changes, this wasn't an issue on my mac before. Do you think this could be related to Apple's restrictions to reading from files without permission? In System Settings under "Privacy & Security" you will find "Files and Folders". I provide full access to Desktop and Documents to Inkscape.

**Comment by felipejoribeiro** [comment]
Hi Rafael,

I find this issue so strange, because it isn’t about the user, or the file system. I use `sudo -u fejori ...` so the user in question is my own user. But for some reason the command just hangs if I try it without sudo:

￼

I will perform the final adjustments now. Maybe I ill discard this change and keep it here locally only.

Best wishes, as always,
Felipe J. O. Ribeiro

**Comment by rpapallas** [comment]
Thanks, @felipejoribeiro. I have now merged your changes. Thank you again for the contribution.

I didn't merge all the changes as I wanted to keep this more general for most people, so you may still need to adjust this to your desire. I didn't document this yet (and by default it's off), you can get prompts for label and caption. If you look at the config, you will see `prompt_label` and `prompt_caption` and if set to true, next time you create a figure it will prompt you for label and caption too.

**Comment by felipejoribeiro** [comment]
That's great! Thanks.

**Comment by felipejoribeiro** [comment]
Great news. I’m happy that some of the changes were useful.

I’m sorry for the other breaking changes that you had to deal with. I wasn’t intending to make a pull request, which made me careless. I was only changing some minor things to quickly make it work perfectly with my setup, as I needed this feature asap haha. But I would be glad to become a maintainer of the project alongside you, if that’s ok. With more careful pull requests in the future.

A feature that would be great would be a “create_and_open_with_template_svg” command, that would prompt the user for what template to use. But before that there are some structural changes that I would like to propose. Will make a pull request with those soon.

Happy Easter!

**Comment by rpapallas** [comment]
Of course! That would be great. The search and use template idea is on the horizon indeed. Hence the concept of templates in the first instance. It would be easy to implement with telescope.

**Comment by felipejoribeiro** [comment]
Hi Rafael,

I was thinking if you would mind if I used my fork of  the project with the intent to create a new package, because I had in mind something more focused on Inkscape and markdown, with simplicity as a priority. Is that ok? My fork is from the commit `51e860de0d6d06feaa49234f47d7426fc522b9f2`.

The structure of the code has changed quite a lot, to the point where any merge attempts are really daunting. And I would like to keep the code base small. I would change the package name and start something new, “svgo” or something hehe

Best wishes, 
Felipe J. O. Ribeiro

**Comment by rpapallas** [comment]
Hi Felipe,

Of course; just please keep a reference back to the original repo and use a different name of the fork to avoid confusion.

Rafael

**Comment by felipejoribeiro** [comment]
Ok! Thank you

Felipe

**Pull request merged**
